---
- hosts: all
  remote_user: root
  tasks:
    - name: "Install Ruby"
      apt:
        name: ruby-full
    - name: Update gems
      shell: gem update --system
    - name: Install bundler
      shell: gem install bundler
      args:
        chdir: /app
